namespace JVMParser;

public enum JVMConstantPoolTag : byte
{
    /// <summary>
    /// Dummy tag for tag padding for double long tags.
    /// </summary>
    _DUMMY = 0,
    UTF8 = 1,
    INTEGER = 3,
    FLOAT = 4,
    LONG = 5,
    DOUBLE = 6,
    CLASS = 7,
    STRING = 8,
    FIELD_REF = 9,
    METHOD_REF = 10,
    INTERFACE_METHOD_REF = 11,
    NAME_AND_TYPE = 12,
    METHOD_HANDLE = 15,
    METHOD_TYPE = 16,
    DYNAMIC = 17,
    INVOKE_DYNAMIC = 18,
    MODULE = 19,
    PACKAGE = 20,
}

public enum JVMReferenceKind : byte
{
    GET_FIELD = 1,
    GET_STATIC = 2,
    PUT_FIELD = 3,
    PUT_STATIC = 4,
    INVOKE_VIRTUAL = 5,
    INVOKE_STATIC = 6,
    INVOKE_SPECIAL = 7,
    NEW_INVOKE_SPECIAL = 8,
    INVOKE_INTERFACE = 9,
}

public enum JVMAccessFlag : ushort
{
    ///<summary>
    /// Declared public; may be accessed from outside its package.
    ///</summary>
    PUBLIC = 0x0001,
    ///<summary>
    /// Declared private; accessible only within the defining class and other classes belonging to the same nest.
    ///</summary>
    PRIVATE = 0x0002,
    ///<summary>
    /// Declared protected; may be accessed within subclasses.
    ///</summary>
    PROTECTED = 0x0004,
    ///<summary>
    /// Declared static.
    ///</summary>
    STATIC = 0x0008,
    ///<summary>
    /// Declared final; no subclasses allowed.<br/>
    /// Declared final; must not be overridden.
    ///</summary>
    FINAL = 0x0010,
    ///<summary>
    /// Treat superclass methods specially when invoked by the invokespecial instruction.<br/>
    /// Declared final; never directly assigned to after object construction.<br/>
    /// FOR METHODS: Declared synchronized; invocation is wrapped by a monitor use.
    ///</summary>
    SUPER_OR_SYNCHRONIZED = 0x0020,
    /// <summary>
    /// Declared volatile; cannot be cached.<br/>
    /// FOR METHODS: A bridge method, generated by the compiler.
    /// </summary>
    VOLATILE_OR_BRIDGE = 0x0040,
    /// <summary>
    /// Declared transient; not written or read by a persistent object manager.<br/>
    /// FOR METHODS: Declared with variable number of arguments.
    /// </summary>
    TRANSIENT_OR_VARARGS = 0x0080,
    /// <summary>
    /// Declared native; implemented in a language other than the Java programming language.
    /// </summary>
    NATIVE = 0x0100,
    ///<summary>
    /// Is an interface, not a class.
    ///</summary>
    INTERFACE = 0x0200,
    ///<summary>
    /// Declared abstract; must not be instantiated.<br/>
    /// Declared abstract; no implementation is provided.
    ///</summary>
    ABSTRACT = 0x0400,
    /// <summary>
    /// In a class file whose major version number is at least 46 and at most 60: Declared strictfp.
    /// </summary>
    STRICT = 0x0800,
    ///<summary>
    /// Declared synthetic; not present in the source code.
    ///</summary>
    SYNTHETIC = 0x1000,
    ///<summary>
    /// Declared as an annotation interface.
    ///</summary>
    ANNOTATION = 0x2000,
    ///<summary>
    /// Declared as an enum class.<br/>
    /// Declared as an element of an enum class. 
    ///</summary>
    ENUM = 0x4000,
    /// <summary>
    /// Is a module, not a class or interface.
    /// </summary>
    MODULE = 0x8000,
}

public enum JVMFieldType
{
    BYTE,
    CHAR,
    DOUBLE,
    FLOAT,
    INT,
    LONG,
    SHORT,
    BOOL,
}
