namespace JVMParser;

public enum JVMConstantPoolTag : byte
{
    /// <summary>
    /// Dummy tag for tag padding for double long tags.
    /// </summary>
    _DUMMY = 0,
    UTF8 = 1,
    INTEGER = 3,
    FLOAT = 4,
    LONG = 5,
    DOUBLE = 6,
    CLASS = 7,
    STRING = 8,
    FIELD_REF = 9,
    METHOD_REF = 10,
    INTERFACE_METHOD_REF = 11,
    NAME_AND_TYPE = 12,
    METHOD_HANDLE = 15,
    METHOD_TYPE = 16,
    DYNAMIC = 17,
    INVOKE_DYNAMIC = 18,
    MODULE = 19,
    PACKAGE = 20,
}

public enum JVMReferenceKind : byte
{
    GET_FIELD = 1,
    GET_STATIC = 2,
    PUT_FIELD = 3,
    PUT_STATIC = 4,
    INVOKE_VIRTUAL = 5,
    INVOKE_STATIC = 6,
    INVOKE_SPECIAL = 7,
    NEW_INVOKE_SPECIAL = 8,
    INVOKE_INTERFACE = 9,
}

public enum JVMAccessFlag : ushort
{
    ///<summary>
    /// Declared public; may be accessed from outside its package.
    ///</summary>
    PUBLIC = 0x0001,
    ///<summary>
    /// Declared private; accessible only within the defining class and other classes belonging to the same nest.
    ///</summary>
    PRIVATE = 0x0002,
    ///<summary>
    /// Declared protected; may be accessed within subclasses.
    ///</summary>
    PROTECTED = 0x0004,
    ///<summary>
    /// Declared static.
    ///</summary>
    STATIC = 0x0008,
    ///<summary>
    /// Declared final; no subclasses allowed.<br/>
    /// Declared final; must not be overridden.
    ///</summary>
    FINAL = 0x0010,
    ///<summary>
    /// Treat superclass methods specially when invoked by the invokespecial instruction.<br/>
    /// Declared final; never directly assigned to after object construction.<br/>
    /// FOR METHODS: Declared synchronized; invocation is wrapped by a monitor use.
    ///</summary>
    SUPER_OR_SYNCHRONIZED = 0x0020,
    /// <summary>
    /// Declared volatile; cannot be cached.<br/>
    /// FOR METHODS: A bridge method, generated by the compiler.
    /// </summary>
    VOLATILE_OR_BRIDGE = 0x0040,
    /// <summary>
    /// Declared transient; not written or read by a persistent object manager.<br/>
    /// FOR METHODS: Declared with variable number of arguments.
    /// </summary>
    TRANSIENT_OR_VARARGS = 0x0080,
    /// <summary>
    /// Declared native; implemented in a language other than the Java programming language.
    /// </summary>
    NATIVE = 0x0100,
    ///<summary>
    /// Is an interface, not a class.
    ///</summary>
    INTERFACE = 0x0200,
    ///<summary>
    /// Declared abstract; must not be instantiated.<br/>
    /// Declared abstract; no implementation is provided.
    ///</summary>
    ABSTRACT = 0x0400,
    /// <summary>
    /// In a class file whose major version number is at least 46 and at most 60: Declared strictfp.
    /// </summary>
    STRICT = 0x0800,
    ///<summary>
    /// Declared synthetic; not present in the source code.
    ///</summary>
    SYNTHETIC = 0x1000,
    ///<summary>
    /// Declared as an annotation interface.
    ///</summary>
    ANNOTATION = 0x2000,
    ///<summary>
    /// Declared as an enum class.<br/>
    /// Declared as an element of an enum class. 
    ///</summary>
    ENUM = 0x4000,
    /// <summary>
    /// Is a module, not a class or interface.
    /// </summary>
    MODULE = 0x8000,
}

public enum JVMFieldType
{
    BYTE,
    CHAR,
    DOUBLE,
    FLOAT,
    INT,
    LONG,
    SHORT,
    BOOL,
}

public enum JVMStackMapFrameType
{
    /// <summary>
    /// 0-63
    /// </summary>
    SAME_FRAME,
    /// <summary>
    /// 64-127
    /// </summary>
    SAME_LOCALS_1_STACK_ITEM_FRAME,
    /// <summary>
    /// 247
    /// </summary>
    SAME_LOCALS_1_STACK_ITEM_FRAME_EXTENDED,
    /// <summary>
    /// 248-250
    /// </summary>
    CHOP_FRAME,
    /// <summary>
    /// 251
    /// </summary>
    SAME_FRAME_EXTENDED,
    /// <summary>
    /// 252-254
    /// </summary>
    APPEND_FRAME,
    /// <summary>
    /// 255
    /// </summary>
    FULL_FRAME,
}

public enum JVMVerificationType : byte
{
    TOP = 0,
    INT = 1,
    FLOAT = 2,
    DOUBLE = 3,
    LONG = 4,
    NULL = 5,
    UNINITIALIZED_THIS = 6,
    OBJECT = 7,
    UNINITIALIZED = 8,
}

public enum JVMOpcode : byte
{
    /// <summary>
    /// Do nothing.
    /// </summary>
    NOP = 0x0,
    /// <summary>
    /// Push null.
    /// </summary>
    ACONST_NULL = 0x1,
    /// <summary>
    /// Push int constant -1.
    /// </summary>
    ICONST_NEG_1 = 0x2,
    /// <summary>
    /// Push int constant 0.
    /// </summary>
    ICONST_0 = 0x3,
    /// <summary>
    /// Push int constant 1.
    /// </summary>
    ICONST_1 = 0x4,
    /// <summary>
    /// Push int constant 2.
    /// </summary>
    ICONST_2 = 0x5,
    /// <summary>
    /// Push int constant 3.
    /// </summary>
    ICONST_3 = 0x6,
    /// <summary>
    /// Push int constant 4.
    /// </summary>
    ICONST_4 = 0x7,
    /// <summary>
    /// Push int constant 5.
    /// </summary>
    ICONST_5 = 0x8,
    /// <summary>
    /// Push long or double from run-time constant pool (wide index).
    /// </summary>
    LOAD_CONST_WIDE = 0x14,
    /// <summary>
    /// Push item from run-time constant pool.
    /// </summary>
    LDC = 0x12,
    /// <summary>
    /// Load double from 1. local variable.
    /// </summary>
    DLOAD_0 = 0x26,
    /// <summary>
    /// Load double from 2. local variable.
    /// </summary>
    DLOAD_1 = 0x27,
    /// <summary>
    /// Load double from 3. local variable.
    /// </summary>
    DLOAD_2 = 0x28,
    /// <summary>
    /// Load double from 4. local variable.
    /// </summary>
    DLOAD_3 = 0x29,
    /// <summary>
    /// Load reference from 1. local variable.
    /// </summary>
    ALOAD_0 = 0x2A,
    /// <summary>
    /// Load reference from 2. local variable.
    /// </summary>
    ALOAD_1 = 0x2B,
    /// <summary>
    /// Load reference from 3. local variable.
    /// </summary>
    ALOAD_2 = 0x2C,
    /// <summary>
    /// Load reference from 4. local variable.
    /// </summary>
    ALOAD_3 = 0x2D,
    /// <summary>
    /// Store reference into 1. local variable.
    /// </summary>
    ASTORE_0 = 0x4b,
    /// <summary>
    /// Store reference into 2. local variable.
    /// </summary>
    ASTORE_1 = 0x4c,
    /// <summary>
    /// Store reference into 3. local variable.
    /// </summary>
    ASTORE_2 = 0x4d,
    /// <summary>
    /// Store reference into 4. local variable.
    /// </summary>
    ASTORE_3 = 0x4e,
    /// <summary>
    /// Store into double array.
    /// </summary>
    DASTORE = 0x52,
    /// <summary>
    /// Duplicate the top operand stack value.
    /// </summary>
    DUP = 0x59,
    /// <summary>
    /// Return reference from method.
    /// </summary>
    ARETURN = 0xb0,
    /// <summary>
    /// Return void from method.
    /// </summary>
    RETURN = 0xb1,
    /// <summary>
    /// Get static field from class.
    /// </summary>
    GET_STATIC = 0xb2,
    /// <summary>
    /// Set field in object.
    /// </summary>
    PUT_FIELD = 0xb5,
    /// <summary>
    /// Invoke instance method; dispatch based on class.
    /// </summary>
    INVOKE_VIRTUAL = 0xb6,
    /// <summary>
    /// Invoke instance method; special handling for superclass, private, and instance initialization method invocations.
    /// </summary>
    INVOKE_SPECIAL = 0xb7,
    /// <summary>
    /// Create new object.
    /// </summary>
    NEW = 0xbb,
    /// <summary>
    /// Create new array.
    /// </summary>
    NEW_ARRAY = 0xbc,
    /// <summary>
    /// Create new array of reference.
    /// </summary>
    ANEW_ARRAY = 0xbd,
    /// <summary>
    /// Throw exception or error.
    /// </summary>
    ATHROW = 0xbf,
}

public enum JVMArrayType : byte
{
    BOOLEAN = 4,
    CHAR = 5,
    FLOAT = 6,
    DOUBLE = 7,
    BYTE = 8,
    SHORT = 9,
    INT = 10,
    LONG = 11,
}
